# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tag do
    version = "1.0.0"
    commit = git_branch()
    release = get_github_release(url: "jamztang/testFastlane", version: version)

    puts release
    if release
      id = release["id"]
      remove_tag(id)
    end

    set_github_release(
      repository_name: "jamztang/testFastlane",
      api_token: ENV["GITHUB_TOKEN"],
      tag_name: version,
      name: "",
      description: "",
      commitish: commit,
      is_prerelease: true,
      upload_assets: ["resources/test.zip"]
    )

  end

  def remove_tag(id)
    github_api(
      server_url: "https://api.github.com",
      api_token: ENV["GITHUB_TOKEN"],
      http_method: "DELETE",
      path: "/repos/jamztang/testFastlane/releases/#{id}"
    )
  end
end

